# Generated by Django 4.1.5 on 2023-01-27 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Form",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=1)),
                ("date", models.DateField(max_length=8)),
                ("value", models.DecimalField(decimal_places=2, max_digits=10)),
                ("cpf", models.CharField(max_length=11)),
                ("creditCard", models.CharField(max_length=12)),
                ("time", models.TimeField(max_length=6)),
                ("storeOwner", models.CharField(max_length=14)),
                ("storeName", models.CharField(max_length=19)),
            ],
        ),
    ]
