# Generated by Django 4.1.5 on 2023-01-26 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("form_save", "0002_alter_form_value"),
    ]

    operations = [
        migrations.RenameField(
            model_name="form",
            old_name="CPF",
            new_name="cpf",
        ),
        migrations.RenameField(
            model_name="form",
            old_name="CreditCard",
            new_name="creditCard",
        ),
        migrations.RenameField(
            model_name="form",
            old_name="Date",
            new_name="date",
        ),
        migrations.RenameField(
            model_name="form",
            old_name="StoreName",
            new_name="storeName",
        ),
        migrations.RenameField(
            model_name="form",
            old_name="StoreOwner",
            new_name="storeOwner",
        ),
        migrations.RenameField(
            model_name="form",
            old_name="Time",
            new_name="time",
        ),
        migrations.RenameField(
            model_name="form",
            old_name="Type",
            new_name="type",
        ),
        migrations.RenameField(
            model_name="form",
            old_name="Value",
            new_name="value",
        ),
    ]
